import { ViewStyle } from 'react-native';

import { TBoxProps } from './box-types';

type TBoxStyleProps = Omit<TBoxProps, 'style' | 'children'>;

export const buildBoxStyle = (props: TBoxStyleProps): ViewStyle => {
  const {
    w,
    h,
    minW,
    maxW,
    minH,
    maxH,
    bg,
    borderColor,
    borderWidth,
    borderTopWidth,
    borderBottomWidth,
    borderLeftWidth,
    borderRightWidth,
    rounded,
    roundedT,
    roundedB,
    roundedL,
    roundedR,
    align,
    justify,
    gap,
    flex,
    direction,
    wrap,
    m,
    mx,
    my,
    mt,
    mb,
    ml,
    mr,
    p,
    px,
    py,
    pt,
    pb,
    pl,
    pr,
    position,
    top,
    bottom,
    left,
    right,
    overflow,
  } = props;

  return {
    width: w,
    height: h,
    minWidth: minW,
    maxWidth: maxW,
    minHeight: minH,
    maxHeight: maxH,
    backgroundColor: bg,
    borderColor,
    borderWidth,
    borderTopWidth,
    borderBottomWidth,
    borderLeftWidth,
    borderRightWidth,
    borderRadius: rounded,
    borderTopLeftRadius: roundedT ?? roundedL,
    borderTopRightRadius: roundedT ?? roundedR,
    borderBottomLeftRadius: roundedB ?? roundedL,
    borderBottomRightRadius: roundedB ?? roundedR,
    flexDirection: direction,
    alignItems: align,
    justifyContent: justify,
    gap,
    flex,
    flexWrap: wrap,
    margin: m,
    marginHorizontal: mx,
    marginVertical: my,
    marginTop: mt,
    marginBottom: mb,
    marginLeft: ml,
    marginRight: mr,
    padding: p,
    paddingHorizontal: px,
    paddingVertical: py,
    paddingTop: pt,
    paddingBottom: pb,
    paddingLeft: pl,
    paddingRight: pr,
    position,
    top,
    bottom,
    left,
    right,
    overflow,
  };
};
